name = "tinkering-with-durable-objects-server"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm install && npm run build"
upload_format = "modules"
upload_exclude = ["*.map"]

[durable_objects]
bindings = [{name = "COUNTER", class_name = "Counter"}]