compatibility_date = "2021-10-10"

name = "clouds-and-edges-server-dev"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[build.upload]
format = "modules"
dir = "dist"
main = "./main.mjs"
rules = [{type = "Data", globs = ["**/*.html"]}]

[build]
command = "yarn build"

[durable_objects]
bindings = [
  {name = "UserAggregate", class_name = "UserAggregate"},
  {name = "MatchAggregate", class_name = "MatchAggregate"},

  {name = "EventStore", class_name = "EventStore"},

  {name = "UsersProjection", class_name = "UsersProjection"},
  {name = "MatchesProjection", class_name = "MatchesProjection"},

  {name = "MatchCreationProcess", class_name = "MatchCreationProcess"},
  {name = "MatchJoiningProcess", class_name = "MatchJoiningProcess"},
]

# Migrations dont seem to work?!

#[[migrations]]
#tag = "v1"
#new_classes = [
#  "UserAggregate",
#  "MatchAggregate",
#
#  "EventStore",
#
#  "UsersProjection",
#  "MatchesProjection",
#
#  "MatchCreationProcess",
#  "MatchJoiningProcess"
#]
#
#[[migrations]]
#tag = "v2"

[env.main]
name = "clouds-and-edges-server"