name = "tinkering-with-durable-objects-server"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[build.upload]
format = "modules"
dir = "dist"
main = "./main.mjs"
rules = [{type = "Data", globs = ["**/*.html"]}]

[build]
command = "yarn build"

[durable_objects]
bindings = [
  {name = "UserAggregate", class_name = "UserAggregate"},
  {name = "MatchAggregate", class_name = "MatchAggregate"},

  {name = "EventStore", class_name = "EventStore"},

  {name = "UsersProjection", class_name = "UsersProjection"},
  {name = "MatchesProjection", class_name = "MatchesProjection"},
  {name = "OpenMatchesProjection", class_name = "OpenMatchesProjection"},

  {name = "ProposalJoiningProcess", class_name = "ProposalJoiningProcess"},
]