compatibility_date = "2021-10-10"

name = "clouds-and-edges-site-dev"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
workers_dev = true

[site]
bucket = "../site/dist" 
entry-point = "."

[env.main]
name = "clouds-and-edges-site"