name: Build & Deploy

on:
  push:
    branches:
      - main

env:
  NODE_ENV: "production"
  BUILD_NUMBER: ${{ github.run_number }}
  NODE_OPTIONS: "--max_old_space_size=8096"

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 16.6.x

      - name: Debug Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-modules-4-${{ hashFiles('yarn.lock') }}

      # We must set --production=false here because we have NODE_ENV set to "production" at the
      # top level env and thus yarn will NOT install devDependencies unless we use the flag
      - name: yarn install
        run: yarn install --pure-lockfile --production=false

  test:
    needs: install

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 16.6.x

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-modules-4-${{ hashFiles('yarn.lock') }}

      - name: Test Everything
        run: yarn test

  lint:
    needs: install

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 16.6.x

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-modules-4-${{ hashFiles('yarn.lock') }}

      - name: Lint
        run: yarn lint

  build-and-deploy:
    needs: [install, test, lint]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 16.6.x

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-modules-4-${{ hashFiles('yarn.lock') }}

      - name: Install A Few Global tools
        run: yarn global add wrangler

      - name: Ensure Wrangler is Authenticated
        run: wrangler whoami

      - name: Build
        run: yarn build

      # - name: Deploy Server
      #   run: yarn server deploy

      # - name: Deploy Web
      #   if: github.ref != 'refs/heads/main'
      #   run: netlify deploy --dir ./packages/web/dist --alias "${{ github.sha }}"
      #   env:
      #     NETLIFY_SITE_ID: 62cef47d-9f33-42d0-b077-538db26dba42

      # - name: Deploy Web To Production
      #   if: github.ref == 'refs/heads/main'
      #   run: netlify deploy --dir ./packages/web/dist --prod
      #   env:
      #     NETLIFY_SITE_ID: 62cef47d-9f33-42d0-b077-538db26dba42
